spring:
  application:
    name: WanMusic

  datasource:
    url: jdbc:mysql://localhost:3306/wanmusic?useSSL=false&serverTimezone=UTC
    username: root
    password: Duyanh090@

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 7000

jwt:
  secret-string: ${JWT_SECRET}